export const FETCH_FIAT_CURRENCIES = 'FETCH_FIAT_CURRENCIES'
export const SELECT_REFERENCE_CURRENCY = 'SELECT_REFERENCE_CURRENCY'
export const FETCH_CRYPTO_COINS = 'FETCH_CRYPTO_COINS'
export const FETCH_SINGLE_COIN = 'FETCH_SINGLE_COIN'
export const SELECT_COIN = 'SELECT_COIN';
